import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import styles from "../../styles/Home.module.css";
import NftList from "../component/nft/NftList";
import { mintNft } from "../services/contract.service";
// import { mintNft } from "../services/contract.service";
import { mintNftsUsingThirdWeb } from "../services/signature-drop.service";
import Registration from "./registration";

const Details: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nft Detail</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>Detils</main>
    </div>
  );
};

export default Details;
