import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import NftList from "../component/nft/NftList";

const Details: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nft Detail</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>Your Nfts</div>
      <main className={styles.main}>
        <NftList type="user" />
      </main>
    </div>
  );
};

export default Details;
