import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import router from "next/router";
import { useEffect } from "react";
import styles from "../../styles/Home.module.css";
import NftList from "../component/nft/NftList";
import { mintNft } from "../services/contract.service";
// import { mintNft } from "../services/contract.service";
import { mintNftsUsingThirdWeb } from "../services/signature-drop.service";
import Registration from "./registration";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainHeader}>
        <ConnectButton />

        <div className={styles.details}>
          <button
            className={styles.button}
            onClick={() => router.push("/registration")}
          >
            Create NFT
          </button>
        </div>
      </div>
      <main className={styles.main}>
        <NftList type="home" />
        {/* <Registration /> */}
      </main>
    </div>
  );
};

export default Home;
