import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import styles from "../../styles/Home.module.css";
import { mintNft } from "../services/contract.service";
import { mintNftsUsingThirdWeb } from "../services/signature-drop.service";
import Registration from "./registration";

const Home: NextPage = () => {
  const metadatas = [
    {
      name: "Cool NFT",
      description: "This is a cool NFT",
      image: "https://www.google.com", // This can be an image url or file
    },
  ];

  useEffect(() => {
    console.log("hello there");
    mintNft(metadatas);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <Registration />
      </main>
    </div>
  );
};

export default Home;
