import { useFormik } from "formik";
import Head from "next/head";
import Router from "next/router";
import { toast } from "react-toastify";
import styles from "./registraion.module.scss";
import { SignUpSchema } from "./RegistraionSchema";

const RegistrationForm = () => {
  const SignUpFormik = useFormik({
    initialValues: {
      name: "",
      description: "",
      quantity: "",
      price: "",
    },
    validationSchema: SignUpSchema,
    onSubmit: async (values, onSubmitProps) => {
      try {
        console.log(values, "Values____");
        const data = {
          name: values.name,
          description: values.description,
          quantity: values.quantity,
          price: values.price,
        };
        // await Register(data);
        toast.success("You Signed Up Successfuly");
        Router.push("/");
        onSubmitProps.resetForm();
      } catch (error) {
        toast.error(error.response.data.message, { position: "top-center" });
      }
    },
  });

  return (
    <>
      <Head>
        <title>NFT Registraion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <div className={styles.container}>
          <div className={styles.signup}>
            <div className={styles.left}>
              <div className={styles.heading}>Register Now !</div>
              <form
                className={styles.formsection}
                onSubmit={SignUpFormik.handleSubmit}
              >
                <div className={styles.inputdiv}>
                  <input
                    type="text"
                    placeholder="Name *"
                    {...SignUpFormik.getFieldProps("name")}
                  />
                </div>
                <div className={styles.inputdiv}>
                  <input
                    type="email"
                    placeholder="Description *"
                    {...SignUpFormik.getFieldProps("description")}
                  />
                </div>
                <div className={styles.inputdiv}>
                  <input
                    type="text"
                    placeholder="Quantity *"
                    {...SignUpFormik.getFieldProps("quantity")}
                  />
                </div>
                <div className={styles.inputdiv}>
                  <input
                    type="text"
                    placeholder="Price"
                    {...SignUpFormik.getFieldProps("price")}
                  />
                </div>
                <div className={styles.inputdiv}>
                  <input type="file" />
                </div>

                <div className={styles.signupbtn}>
                  <button type="submit">Register</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default RegistrationForm;
